"""
Function tools for the AI agent.

Instead of a fixed set of hard-coded query functions, the agent is given a
schema-inspection tool and a single SQL-execution tool. The actual queries are
generated by the LLM at runtime and run (read-only) against an in-memory SQLite
database, so the agent can answer arbitrary analytical questions rather than
only the ones we anticipated.
"""
from typing import Dict, List, Any
from database import DataManager, TABLE_NAME
from utils import setup_logger, log_function_call
from config import MAX_RESULTS_TO_LLM

logger = setup_logger(__name__)


class AgentTools:
    """
    Collection of tools available to the AI agent for student performance data.
    """

    def __init__(self, data_manager: DataManager):
        """
        Initializes tools with DataManager instance.
        Inputs: data_manager (DataManager)
        Outputs: None
        """
        self.data_manager = data_manager
        logger.info("AgentTools initialized")

    def get_database_schema(self) -> Dict[str, Any]:
        """
        Returns the schema of the queryable table so the agent knows which
        columns and values exist before writing SQL.
        Inputs: None
        Outputs: dictionary with the schema description
        """
        log_function_call("get_database_schema", {})

        return {
            "success": True,
            "table": TABLE_NAME,
            "schema": self.data_manager.get_schema_description(),
        }

    def execute_sql_query(self, sql: str, limit: int = MAX_RESULTS_TO_LLM) -> Dict[str, Any]:
        """
        Executes an AI-generated read-only SQL query against the student
        performance database.
        Inputs: sql (string, a single SELECT statement), limit (int)
        Outputs: dictionary with query results and metadata
        """
        log_function_call("execute_sql_query", {"sql": sql, "limit": limit})

        return self.data_manager.execute_query(sql, limit=limit)

    def get_tool_definitions(self) -> List[Dict]:
        """
        Returns OpenAI function definitions for all available tools.
        Inputs: None
        Outputs: list of tool definitions in OpenAI format
        """
        return [
            {
                "type": "function",
                "function": {
                    "name": "get_database_schema",
                    "description": (
                        "Return the schema of the student performance database: "
                        "the table name, its columns with types, and the possible "
                        "values for categorical columns. Call this first if you are "
                        "unsure about column names or valid filter values before "
                        "writing a SQL query."
                    ),
                    "parameters": {
                        "type": "object",
                        "properties": {},
                        "required": [],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "execute_sql_query",
                    "description": (
                        "Run a single read-only SQLite SELECT query against the "
                        f"'{TABLE_NAME}' table and return the resulting rows. Use this "
                        "to answer any question about the student performance data: "
                        "filtering, aggregation (AVG/COUNT/SUM/MIN/MAX), grouping, "
                        "ranking/top-N, percentiles, and comparisons are all "
                        "supported. Only SELECT/WITH statements are allowed; write "
                        "operations (INSERT/UPDATE/DELETE/DROP/etc.) are blocked. "
                        "Call get_database_schema first if unsure of column names."
                    ),
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "sql": {
                                "type": "string",
                                "description": (
                                    "A single, valid SQLite SELECT statement querying "
                                    f"the '{TABLE_NAME}' table. Do not include multiple "
                                    "statements or a trailing semicolon-separated batch."
                                ),
                            },
                            "limit": {
                                "type": "integer",
                                "description": (
                                    "Maximum number of rows to return (default "
                                    f"{MAX_RESULTS_TO_LLM}). A LIMIT is enforced "
                                    "automatically if your query omits one."
                                ),
                                "default": MAX_RESULTS_TO_LLM,
                            },
                        },
                        "required": ["sql"],
                    },
                },
            },
        ]
